baseURL = 'https://jacmoe.github.io/hotel-california-of-creative-writing/'
languageCode = 'en-us'
title = "Hotel California of Creative Writing"
publishDir = "docs"
theme = "hugo-theme-relearn"

[outputs]
  home = ["HTML", "RSS", "PRINT", "SEARCH"]
  section = ["HTML", "RSS", "PRINT"]
  page = ["HTML", "RSS", "PRINT"]

[params]
  themeVariant = [ "zen-light", "zen-dark" ]

[markup.goldmark.renderer]
unsafe = true
