baseURL = "https://jacmoe.github.io/hccw/"
languageCode = "en-us"
title = "Hotel California of Creative Writing"
publishDir = "docs"
theme = "hugo-theme-relearn"
canonifyURLs = true
relativeURLs = true

[outputs]
  home = ["HTML", "RSS", "PRINT", "SEARCH"]
  section = ["HTML", "RSS", "PRINT"]
  page = ["HTML", "RSS", "PRINT"]

[params]
  themeVariant = [ "zen-dark", "zen-light" ]
  disableExplicitIndexURLs = true

[markup.goldmark.renderer]
unsafe = true
